name: 🐛 Bug Report
description: Something isn't working as I expected. 🤔
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: demo
    attributes:
      label: Demo
      description: If relevant, provide a link to a live demo.
      placeholder: For a live demo of the issue, see 
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the issue.
      value: "Encountered an error when "
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Reproduction
      description: What steps are required to reproduce the unexpected output?
      value: |
        - a
        - b
        - c
      render: shell
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please ensure the following tasks are completed before filing a bug report.
      options:
        - label: Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
          required: true
        - label:  Searched for existing issues and pull requests.
          required: true
