name: 🐛 Bug Report
description: Something isn't working as I expected. 🤔
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the issue.
      value: "Encountered an error when "
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Related Issues
      description: Does this issue have any related issues?
      value: "Related issues # , # , and # ."
  - type: textarea
    id: questions
    attributes:
      label: Questions
      description: Any questions for reviewers?
      value: No.
  - type: input
    id: demo
    attributes:
      label: Demo
      description: If relevant, provide a link to a live demo.
      placeholder: For a live demo of the issue, see 
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: What steps are required to reproduce the unexpected output?
      value: |
        - a
        - b
        - c
      render: shell
  - type: textarea
    id: expected
    attributes:
      label: Expected Results
      description: What are the expected results?
      placeholder: Insert expected results here
      render: shell
  - type: textarea
    id: actual
    attributes:
      label: Actual Results
      description: What are the actual results?
      placeholder: Insert actual results here
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of `stdlib` are you running?
  - type: dropdown
    id: environments
    attributes:
      label: What environments are affected?
      multiple: true
      options:
        - Node.js
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - N/A
      placeholder: N/A
  - type: input
    id: environment-version
    attributes:
      label: What environment version(s)?
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please ensure the following tasks are completed before filing a bug report.
      options:
        - label: Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
          required: true
        - label:  Searched for existing issues and pull requests.
          required: true
