name: Pass Tests

on:
  workflow_dispatch:

jobs:
  utils-property-symbols:
   runs-on: ubuntu-latest
   steps:
   - name: 'Checkout repository'
     uses: actions/checkout@v2
     with:
       clean: true
       fetch-depth: 100
       lfs: false
     timeout-minutes: 10
   - name: Install dependencies
     run: |
       echo $( git rev-parse --show-toplevel )
       echo $( git config --get remote.origin.url )
